/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health Check */
    get: operations["health_check_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Jobs
     * @description List all jobs (oldest first, FIFO order).
     */
    get: operations["list_jobs_jobs_get"];
    put?: never;
    /**
     * Create Job
     * @description Create a new sync job.
     *
     *     Jobs are queued and executed sequentially. Returns 409 only if queue is full.
     */
    post: operations["create_job_jobs_post"];
    /**
     * Clear Jobs
     * @description Clear all completed/failed jobs.
     *
     *     Running jobs are not affected.
     */
    delete: operations["clear_jobs_jobs_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/jobs/{job_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancel Job
     * @description Cancel a running or queued job.
     *
     *     Returns 404 if job not found, 409 if job already finished.
     */
    post: operations["cancel_job_jobs__job_id__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/jobs/{job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Job
     * @description Delete a completed, failed, or cancelled job.
     *
     *     Running jobs cannot be deleted (returns 409).
     */
    delete: operations["delete_job_jobs__job_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/logs/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get buffered log entries
     * @description Returns all currently buffered log entries as an array.
     */
    get: operations["get_log_history_logs_history_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/logs/sse": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Stream structured logs via SSE
     * @description Each SSE data line contains a JSON-serialized LogEntry object.
     */
    get: operations["stream_logs_logs_sse_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/cookies/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Cookies Status
     * @description Check if cookies file is configured.
     */
    get: operations["cookies_status_cookies_status_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/cookies": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload Cookies
     * @description Upload cookies.txt content (Netscape format).
     */
    post: operations["upload_cookies_cookies_post"];
    /**
     * Delete Cookies
     * @description Delete cookies file.
     */
    delete: operations["delete_cookies_cookies_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AlbumInfo
     * @description Information about an album/playlist.
     */
    AlbumInfo: {
      /** Title */
      title: string;
      /** Artist */
      artist: string;
      /** Year */
      year?: number | null;
      /** Track Count */
      track_count: number;
      /**
       * Playlist Id
       * @default
       */
      playlist_id: string;
      /**
       * Url
       * @default
       */
      url: string;
      /** Thumbnail Url */
      thumbnail_url?: string | null;
      /** Audio Codec */
      audio_codec?: string | null;
      /** Audio Bitrate */
      audio_bitrate?: number | null;
      /**
       * Kind
       * @default playlist
       */
      kind: string;
    };
    /**
     * AudioCodec
     * @description Supported audio output codecs.
     * @enum {string}
     */
    AudioCodec: "opus" | "mp3" | "m4a";
    /**
     * CancelJobResponse
     * @description Response when a job is cancelled.
     */
    CancelJobResponse: {
      /**
       * Message
       * @default Job cancelled
       * @constant
       */
      message: "Job cancelled";
    };
    /**
     * ClearJobsResponse
     * @description Response when jobs are cleared.
     */
    ClearJobsResponse: {
      /** Cleared */
      cleared: number;
    };
    /**
     * CookiesStatusResponse
     * @description Cookies status response model.
     */
    CookiesStatusResponse: {
      /** Configured */
      configured: boolean;
    };
    /**
     * CookiesUploadRequest
     * @description Cookies upload request model.
     */
    CookiesUploadRequest: {
      /** Content */
      content: string;
    };
    /**
     * CookiesUploadResponse
     * @description Cookies upload response model.
     */
    CookiesUploadResponse: {
      /**
       * Status
       * @constant
       */
      status: "ok";
    };
    /**
     * CreateJobRequest
     * @description Request to create a new sync job.
     */
    CreateJobRequest: {
      /** Url */
      url: string;
      audio_format?: components["schemas"]["AudioCodec"] | null;
      /** Max Items */
      max_items?: number | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HealthResponse
     * @description Health check response model.
     */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: "healthy";
    };
    /**
     * Job
     * @description A background sync job.
     */
    Job: {
      /** Id */
      id: string;
      /** Url */
      url: string;
      /** @default opus */
      audio_format: components["schemas"]["AudioCodec"];
      /** Max Items */
      max_items?: number | null;
      /** @default pending */
      status: components["schemas"]["JobStatus"];
      /**
       * Progress
       * @default 0
       */
      progress: number;
      album_info?: components["schemas"]["AlbumInfo"] | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at?: string;
      /** Started At */
      started_at?: string | null;
      /** Completed At */
      completed_at?: string | null;
    };
    /**
     * JobConflictErrorResponse
     * @description Error response when job creation is rejected.
     */
    JobConflictErrorResponse: {
      /**
       * Error
       * @enum {string}
       */
      error: "A job is already running" | "Queue is full";
      /** Active Job Id */
      active_job_id?: string | null;
    };
    /**
     * JobCreatedResponse
     * @description Response when a job is created.
     */
    JobCreatedResponse: {
      /** Id */
      id: string;
      /**
       * Message
       * @default Job created
       * @constant
       */
      message: "Job created";
    };
    /**
     * JobStatus
     * @description Status of a background job.
     * @enum {string}
     */
    JobStatus:
      | "pending"
      | "fetching_info"
      | "downloading"
      | "importing"
      | "completed"
      | "failed"
      | "cancelled";
    /**
     * JobsResponse
     * @description Response for listing jobs.
     */
    JobsResponse: {
      /** Jobs */
      jobs: components["schemas"]["Job"][];
    };
    /**
     * LogEntry
     * @description Structured log entry sent to frontend via SSE.
     *
     *     Each log line from the backend is serialized as JSON using this schema.
     *     The frontend parses these entries and applies theme-aware styling.
     *
     *     The `entry_type` field enables discriminated union pattern matching
     *     in TypeScript for exhaustive type narrowing.
     * @example {
     *       "entry_type": "phase",
     *       "level": "INFO",
     *       "message": "Extracting metadata from playlist",
     *       "phase": "extracting",
     *       "phase_num": 1,
     *       "timestamp": "11:09:53"
     *     }
     * @example {
     *       "current": 1,
     *       "entry_type": "progress",
     *       "event_type": "track_download",
     *       "level": "INFO",
     *       "message": "Queen - Bohemian Rhapsody",
     *       "timestamp": "11:09:54",
     *       "total": 10,
     *       "track_artist": "Queen",
     *       "track_title": "Bohemian Rhapsody"
     *     }
     * @example {
     *       "entry_type": "stats",
     *       "level": "INFO",
     *       "message": "Downloads complete",
     *       "stats": {
     *         "failed": 0,
     *         "skipped": 2,
     *         "success": 8
     *       },
     *       "timestamp": "11:09:55"
     *     }
     */
    LogEntry: {
      /**
       * Entry Type
       * @description Entry type for discriminated union matching
       * @default default
       * @enum {string}
       */
      entry_type:
        | "header"
        | "phase"
        | "stats"
        | "progress"
        | "status"
        | "file"
        | "default";
      /**
       * Timestamp
       * @description Log timestamp in HH:MM:SS format
       */
      timestamp: string;
      /**
       * Level
       * @description Log level: DEBUG, INFO, WARNING, ERROR
       */
      level: string;
      /**
       * Message
       * @description Human-readable log message
       */
      message: string;
      /**
       * Phase
       * @description Current operation phase: extracting, downloading, composing
       */
      phase?: string | null;
      /**
       * Phase Num
       * @description Phase number (1, 2, 3)
       */
      phase_num?: number | null;
      /**
       * Event Type
       * @description Specific event type for granular tracking
       */
      event_type?: string | null;
      /**
       * Current
       * @description Current item index in progress (0-indexed)
       */
      current?: number | null;
      /**
       * Total
       * @description Total number of items to process
       */
      total?: number | null;
      /**
       * Status
       * @description Operation result status
       */
      status?: ("success" | "skipped" | "failed") | null;
      /** @description Aggregate statistics for batch operations */
      stats?: components["schemas"]["LogStats"] | null;
      /**
       * File Path
       * @description Path to generated or downloaded file
       */
      file_path?: string | null;
      /**
       * File Type
       * @description Type of file: m3u, cover, audio
       */
      file_type?: string | null;
      /**
       * Track Title
       * @description Track title being processed
       */
      track_title?: string | null;
      /**
       * Track Artist
       * @description Track artist name
       */
      track_artist?: string | null;
      /**
       * Header
       * @description Section header text for visual separation
       */
      header?: string | null;
    };
    /**
     * LogStats
     * @description Statistics for batch operations.
     */
    LogStats: {
      /** Success */
      success?: number | null;
      /** Skipped */
      skipped?: number | null;
      /** Failed */
      failed?: number | null;
      /** Extracted */
      extracted?: number | null;
      /** Unavailable */
      unavailable?: number | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_check_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  list_jobs_jobs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobsResponse"];
        };
      };
    };
  };
  create_job_jobs_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateJobRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobCreatedResponse"];
        };
      };
      /** @description Queue is full */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobConflictErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  clear_jobs_jobs_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClearJobsResponse"];
        };
      };
    };
  };
  cancel_job_jobs__job_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CancelJobResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_job_jobs__job_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_log_history_logs_history_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LogEntry"][];
        };
      };
    };
  };
  stream_logs_logs_sse_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  cookies_status_cookies_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CookiesStatusResponse"];
        };
      };
    };
  };
  upload_cookies_cookies_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CookiesUploadRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CookiesUploadResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_cookies_cookies_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CookiesUploadResponse"];
        };
      };
    };
  };
}
